[package]
name = "workspace-entity"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
tokio = { version = "1", features = ["full"] }
sea-orm = { version = "^2.0.0-rc", features = [
  "sqlx-postgres",
  "runtime-tokio-native-tls",
] }
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1" }
futures-util = { version = "0.3" }
